{
 "title": "Solar",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Gesamt Erzeugung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"SOLAR_OVERVIEW\" and\n    r._field == \"eTotal\"\n  )"
    }
   ]
  },
  {
   "title": "Tag Gesamt ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"SOLAR_OVERVIEW\" and\n    r._field == \"eToday\"\n  )"
    }
   ]
  },
  {
   "title": "Solar Tagesübersicht Leistung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"SOLAR_HOURLY\" and\n    r._field == \"gridPower\"\n  )"
    }
   ]
  },
  {
   "title": "Tages Erzeugung Strom",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"SOLAR_HOURLY\" and\n    r._field == \"gridCurrent\"\n\n  )"
    }
   ]
  },
  {
   "title": "Weitere Daten",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: today())\n  |> filter(fn: (r) =>\n    r._measurement == \"SOLAR_HOURLY\" and\n    r._field == \"pv1Voltage\" or \n    r._field == \"pv1Current\" or\n    r._field == \"pv1Power\"  \n  )"
    }
   ]
  },
  {
   "title": "Inverter Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"SOLAR_HOURLY\" and\n    r._field == \"temp\"\n  )"
    }
   ]
  }
 ]
}